#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define UIP_CONF_BUFFER_SIZE 240

/* Disable all logging to save ROM */
#define LOG_CONF_LEVEL LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_TCPIP LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_NONE

/* Reduce CoAP memory usage */
#define COAP_MAX_CHUNK_SIZE 64

#endif