CONTIKI_PROJECT = coap-example-routing

all: $(CONTIKI_PROJECT)

# Add the routing gateway resource source
PROJECT_SOURCEFILES += res-routing-gateway.c

# Contiki path
CONTIKI ?= ../../../..

include $(CONTIKI)/Makefile.include